"""add correlations and mitre_tags to findings

Revision ID: 4ca0fbaa138b
Revises: bfa285a7b4bf
Create Date: 2026-09-15 09:10:18.353269

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4ca0fbaa138b"
down_revision: str | None = "bfa285a7b4bf"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("findings", sa.Column("correlations", sa.JSON(), nullable=True))
    op.add_column("findings", sa.Column("mitre_tags", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("findings", "mitre_tags")
    op.drop_column("findings", "correlations")
    # ### end Alembic commands ###
