"""add enrichments column to findings

Revision ID: bfa285a7b4bf
Revises: 0002
Create Date: 2026-08-21 21:31:06.575431

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bfa285a7b4bf"
down_revision: str | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("findings", sa.Column("enrichments", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("findings", "enrichments")
    # ### end Alembic commands ###
